
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'vigneshs-saas'
    targetResolveRepo: 'nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true